sonar.projectKey= Alev9k_PROGETTO_Share
sonar.organization= alev9k
sonar.host.url= https://sonarcloud.io

# Percorsi sorgenti e test
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Fondamentale per il Code Coverage (requisito esame)
sonar.java.test.binaries=target/test-classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.coverage.exclusions=**/*

# Encoding
sonar.sourceEncoding=UTF-8
